import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, readFileSync, mkdirSync, rmSync, readdirSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { spawnSync } from "node:child_process";
import { resolveVariant } from "./variants.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const run = (dir, args) => spawnSync(process.execPath, [join(ROOT, "setup.mjs"), ...args],
  { encoding: "utf8", env: { ...process.env, CLAUDE_CONFIG_DIR: dir, CLAUDE_SETUP_SKIP_PLUGINS: "1" }, timeout: 120000 });

function walk(dir, rel = "") {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const r = rel ? `${rel}/${e.name}` : e.name;
    if (e.isDirectory()) out.push(...walk(join(dir, e.name), r));
    else out.push(r);
  }
  return out;
}
const FOREIGN = ["settings.local.json", "projects/p/notes.md", "memory/MEMORY.md", "skills/graphify/SKILL.md"];
function plantForeign(dir) {
  for (const f of FOREIGN) { mkdirSync(join(dir, dirname(f)), { recursive: true }); writeFileSync(join(dir, f), `foreign:${f}`); }
}
function assertForeignIntact(dir) {
  for (const f of FOREIGN) assert.equal(readFileSync(join(dir, f), "utf8"), `foreign:${f}`, `foreign file clobbered: ${f}`);
}
function readManifest(dir) {
  return JSON.parse(readFileSync(join(dir, "state/bundle-manifest.json"), "utf8"));
}
// Every rel in `rels` must exist on disk, and every installed file NOT accounted for by the
// installer's own generated-outside-V.rels paths (state/, settings.json, CLAUDE.md) or a planted
// FOREIGN fixture must be IN `rels` - i.e. no surplus. Mirrors the "lite install" test's inline
// checks above, factored out so base (and future profiles) can reuse it.
function assertTreeEquals(dir, rels) {
  const installed = new Set(walk(dir));
  for (const rel of rels) assert.ok(installed.has(rel), `missing: ${rel}`);
  for (const rel of installed)
    if (!rel.startsWith("state/") && rel !== "settings.json" && rel !== "CLAUDE.md" && !FOREIGN.includes(rel))
      assert.ok(rels.includes(rel), `unexpected: ${rel}`);
}

test("no *.test.mjs leaks into any resolved profile (alwaysExclude)", () => {
  for (const variant of ["full", "base", "lite"]) {
    const v = resolveVariant({ repoRoot: ROOT, variant });
    const leaked = v.rels.filter((r) => r.endsWith(".test.mjs"));
    assert.deepEqual(leaked, [], `test files leaked into ${variant}: ${leaked.join(", ")}`);
  }
});

test("lite install: exact tree, 7 hooks, no statusLine, manifest.variant", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-lite-"));
  plantForeign(dir);
  const r = run(dir, ["--variant=lite", "--replace-all"]);
  assert.equal(r.status, 0, r.stderr);
  const v = resolveVariant({ repoRoot: ROOT, variant: "lite" });
  const installed = new Set(walk(dir));
  for (const rel of v.rels) assert.ok(installed.has(rel), `missing: ${rel}`);
  // CLAUDE.md is ASSEMBLED (not a payload rel - payload/claude-md/** is a build input, see
  // assemble-claude-md.mjs) so it's whitelisted here the same way settings.json/state/ are:
  // generated by setup.mjs itself, not mirrored 1:1 from V.rels.
  for (const rel of installed)
    if (!rel.startsWith("state/") && rel !== "settings.json" && rel !== "CLAUDE.md" && !FOREIGN.includes(rel))
      assert.ok(v.rels.includes(rel), `unexpected: ${rel}`);
  const settings = JSON.parse(readFileSync(join(dir, "settings.json"), "utf8"));
  const scripts = new Set();
  for (const entries of Object.values(settings.hooks || {}))
    for (const e of entries) for (const h of (e.hooks || []))
      for (const a of (h.args || [])) scripts.add(String(a).split(/[\\/]/).pop());
  assert.equal(scripts.size, 7);
  assert.ok(!("statusLine" in settings));
  assert.equal(JSON.parse(readFileSync(join(dir, "state/bundle-manifest.json"), "utf8")).variant, "lite");
  // lite CLAUDE.md is the overlay version
  assert.match(readFileSync(join(dir, "CLAUDE.md"), "utf8"), /lite variant/);
  for (const f of FOREIGN) assert.equal(readFileSync(join(dir, f), "utf8"), `foreign:${f}`);
  rmSync(dir, { recursive: true, force: true });
});

test("switch full->lite prunes surplus; lite->full restores; foreign untouched", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-sw-"));
  plantForeign(dir);
  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")));
  assert.equal(run(dir, ["--variant=lite", "--replace-all"]).status, 0);
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook not pruned");
  assert.ok(!existsSync(join(dir, "hooks/lib/context-mode-gsd-agents.mjs")), "gsd lib not pruned (name-gate bypass broken?)");
  assert.ok(!existsSync(join(dir, "gsd-defaults.partial.json")), "gsd-defaults mirror not pruned");
  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "full files not restored");
  assert.equal(JSON.parse(readFileSync(join(dir, "state/bundle-manifest.json"), "utf8")).variant, "full");
  for (const f of FOREIGN) assert.equal(readFileSync(join(dir, f), "utf8"), `foreign:${f}`);
  rmSync(dir, { recursive: true, force: true });
});

test("manifest without variant field = full (no surplus prune on full reinstall)", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-legacy-"));
  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  const mPath = join(dir, "state/bundle-manifest.json");
  const m = JSON.parse(readFileSync(mPath, "utf8"));
  delete m.variant;                      // simulate pre-variant bundle
  writeFileSync(mPath, JSON.stringify(m, null, 2));
  const r = run(dir, ["--replace-all"]); // no flag, non-TTY -> detected = full
  assert.equal(r.status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")));
  rmSync(dir, { recursive: true, force: true });
});

test("manifest profile round-trips and falls back to variant", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-fallback-"));
  assert.equal(run(dir, ["--variant=base", "--replace-all"]).status, 0);
  assert.equal(readManifest(dir).profile, "base");
  assert.equal(readManifest(dir).variant, "base");

  // profile present, variant absent -> profile wins (the current dual-write's primary key).
  const mPath = join(dir, "state/bundle-manifest.json");
  let m = readManifest(dir);
  delete m.variant;
  writeFileSync(mPath, JSON.stringify(m, null, 2));
  assert.equal(run(dir, ["--replace-all"]).status, 0); // no --variant flag: detected from manifest
  assert.equal(readManifest(dir).profile, "base");
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "should stay on base, not fall back to full");

  // NEITHER key present -> true legacy fallback path ("full" default), the case the old
  // "manifest without variant field" test claimed to cover but didn't (it left .profile behind).
  m = readManifest(dir);
  delete m.profile;
  delete m.variant;
  writeFileSync(mPath, JSON.stringify(m, null, 2));
  assert.equal(run(dir, ["--replace-all"]).status, 0);
  assert.equal(readManifest(dir).profile, "full");
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "neither key present -> falls back to full");
  rmSync(dir, { recursive: true, force: true });
});

test("base install: exact tree, base keep-set present, gsd absent, manifest.profile", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-base-"));
  plantForeign(dir);
  const r = run(dir, ["--variant=base", "--skip-all"]);
  assert.equal(r.status, 0, r.stderr);
  const v = resolveVariant({ repoRoot: ROOT, variant: "base" });
  assertTreeEquals(dir, v.rels);
  assert.ok(existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")), "base universal infra hook missing");
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook should be absent on base");
  assert.equal(readManifest(dir).profile, "base");
  assertForeignIntact(dir);
  rmSync(dir, { recursive: true, force: true });
});

test("full->base->lite prunes GSD then universal infra; foreign untouched", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-transitions-"));
  plantForeign(dir);

  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")));
  assert.ok(existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")));
  assertForeignIntact(dir);

  // full -> base: GSD-everything pruned, universal infra (base's own keep-set) stays.
  assert.equal(run(dir, ["--variant=base", "--replace-all"]).status, 0);
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook not pruned on full->base");
  assert.ok(!existsSync(join(dir, "hooks/lib/context-mode-gsd-agents.mjs")), "gsd lib not pruned on full->base");
  assert.ok(!existsSync(join(dir, "gsd-defaults.partial.json")), "gsd-defaults mirror not pruned on full->base");
  assert.ok(existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")), "universal infra wrongly pruned on full->base");
  assert.equal(readManifest(dir).profile, "base");
  assertForeignIntact(dir);

  // base -> lite: the universal infra base kept now gets pruned too.
  assert.equal(run(dir, ["--variant=lite", "--replace-all"]).status, 0);
  assert.ok(!existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")), "universal infra not pruned on base->lite");
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook still absent on lite");
  assert.equal(readManifest(dir).profile, "lite");
  assertForeignIntact(dir);

  rmSync(dir, { recursive: true, force: true });
});

test("augment toggle: base + --configure-neo4j=on adds files; =off prunes them, no manual chain", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-augment-"));
  const neo4jFile = join(dir, "bin/lib/neo4j-config.mjs");

  assert.equal(run(dir, ["--variant=base", "--skip-all"]).status, 0);
  assert.ok(!existsSync(neo4jFile), "neo4j should be off by default on base");
  assert.deepEqual(readManifest(dir).activeOptional, []);

  assert.equal(run(dir, ["--variant=base", "--configure-neo4j=on", "--skip-all"]).status, 0);
  assert.ok(existsSync(neo4jFile), "--configure-neo4j=on should add the file in-process");
  assert.deepEqual(readManifest(dir).activeOptional, ["neo4j"]);

  assert.equal(run(dir, ["--variant=base", "--configure-neo4j=off", "--skip-all"]).status, 0);
  assert.ok(!existsSync(neo4jFile), "--configure-neo4j=off should prune the file in-process");
  assert.deepEqual(readManifest(dir).activeOptional, []);

  rmSync(dir, { recursive: true, force: true });
});

test("lite build ships the AI-dev-mode (A) files", () => {
  const v = resolveVariant({ repoRoot: ROOT, variant: "lite" });
  for (const p of [
    "hooks/inject-axes.mjs",
    "hooks/lib/inject-axes.mjs",
    "hooks/lib/verbosity-rules.mjs",
    "hooks/lib/verbosity-lite-rule.md",
    "commands/aidev.md",
  ]) {
    assert.ok(v.rels.includes(p), `${p} must be in lite`);
  }
});

test("--dry-run writes nothing for both variants", () => {
  for (const variant of ["lite", "full"]) {
    const dir = mkdtempSync(join(tmpdir(), "cc-dry-"));
    const r = run(dir, [`--variant=${variant}`, "--dry-run", "--skip-all"]);
    assert.equal(r.status, 0, r.stderr);
    assert.deepEqual(walk(dir), [], `dry-run wrote files (${variant})`);
    rmSync(dir, { recursive: true, force: true });
  }
});

/* ---------- foreign gsd-core detector (base/lite only) ----------
 * `run()` above is always non-TTY (spawnSync pipes stdin), so the interactive branch needs its own
 * launcher: a driver module that forces process.stdin.isTTY before importing setup.mjs. Paired with
 * --skip-all (BULK => INTERACTIVE=false) every OTHER prompt in setup.mjs is suppressed, so the one
 * question the child asks is the detector's own and the scripted answer cannot be mis-consumed. */
const TTY_DRIVER = (() => {
  const p = join(mkdtempSync(join(tmpdir(), "cc-tty-")), "force-tty.mjs");
  writeFileSync(p, "process.stdin.isTTY = true;\nawait import(process.env.SETUP_URL);\n");
  return p;
})();
const runTty = (dir, args, answer) => spawnSync(process.execPath, [TTY_DRIVER, ...args], {
  encoding: "utf8", input: answer, timeout: 120000,
  env: { ...process.env, CLAUDE_CONFIG_DIR: dir, CLAUDE_SETUP_SKIP_PLUGINS: "1",
    SETUP_URL: pathToFileURL(join(ROOT, "setup.mjs")).href },
});
const GSD_FIXTURE = {
  "gsd-core/VERSION": "0.0.0-test\n",
  "gsd-core/lib/orchestrate.mjs": "x".repeat(3000),
  "skills/gsd-probe/SKILL.md": "x",
  "agents/gsd-planner.md": "x",
  "hooks/gsd-probe.mjs": "x",
  "hooks/lib/gsd-probe-lib.mjs": "x",
};
const GSD_REMOVED = ["gsd-core", "skills/gsd-probe", "agents/gsd-planner.md", "hooks/gsd-probe.mjs", "hooks/lib/gsd-probe-lib.mjs"];
function plantGsdCore(dir) {
  for (const [rel, body] of Object.entries(GSD_FIXTURE)) {
    mkdirSync(join(dir, dirname(rel)), { recursive: true });
    writeFileSync(join(dir, rel), body);
  }
  // Registered under an event settings.partial.json never declares, so the assertion below sees the
  // detector's own filter and not the settings merge's claim-our-slots pass.
  writeFileSync(join(dir, "settings.json"), JSON.stringify({
    hooks: { Notification: [{ matcher: "", hooks: [{ type: "command", command: "node", args: [join(dir, "hooks", "gsd-probe.mjs")] }] }] },
  }, null, 2) + "\n");
}
const gsdPresent = (dir) => existsSync(join(dir, "gsd-core/VERSION"));
const batches = (dir) => (existsSync(join(dir, ".cleanup-trash")) ? readdirSync(join(dir, ".cleanup-trash")) : []);
const NOT_REPORTED = /is installed here and is not part of this bundle/;

test("--uninstall-gsd moves gsd-core to a trash batch, backs settings up first, drops only gsd hooks", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-gsd-"));
  plantGsdCore(dir);

  const dry = run(dir, ["--variant=base", "--uninstall-gsd", "--dry-run", "--skip-all"]);
  assert.equal(dry.status, 0, dry.stderr);
  assert.match(dry.stdout, /\[dry-run\] would move \d+ path\(s\)/);
  assert.ok(gsdPresent(dir), "dry-run removed something");
  assert.deepEqual(batches(dir), []);

  const r = run(dir, ["--variant=base", "--uninstall-gsd", "--skip-all"]);
  assert.equal(r.status, 0, r.stderr);
  assert.match(r.stdout, /gsd-core 0\.0\.0-test is installed here and is not part of this bundle/);
  for (const rel of GSD_REMOVED) assert.ok(!existsSync(join(dir, rel)), `not removed: ${rel}`);

  const ts = batches(dir);
  assert.equal(ts.length, 1, `expected exactly one trash batch, got ${ts.join(", ")}`);
  const batch = join(dir, ".cleanup-trash", ts[0]);
  assert.ok(existsSync(join(batch, "manifest.json")), "batch manifest missing");
  const backup = join(batch, "settings.json.pre-gsd-uninstall");
  assert.ok(existsSync(backup), "pre-edit settings copy missing from the batch");
  assert.equal(JSON.parse(readFileSync(backup, "utf8")).hooks.Notification.length, 1, "backup is not the PRE-edit copy");

  const settings = JSON.parse(readFileSync(join(dir, "settings.json"), "utf8"));
  assert.deepEqual(settings.hooks.Notification, [], "gsd hook entry not removed, or the key was deleted");

  // restoreBatch deletes the whole batch (backup included), so the cp must be printed FIRST.
  const cpAt = r.stdout.indexOf(`cp "`);
  const restoreAt = r.stdout.indexOf(`restore --ts ${ts[0]}`);
  assert.ok(cpAt !== -1, "rollback did not print a cp for settings.json");
  assert.ok(restoreAt !== -1, "rollback did not print the batch restore command with this run's ts");
  assert.ok(cpAt < restoreAt, "rollback prints restore before cp - restoring first destroys the backup");
  rmSync(dir, { recursive: true, force: true });
});

test("--replace-all is never consent to uninstall a foreign product", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-gsd-bulk-"));
  plantGsdCore(dir);
  const r = run(dir, ["--variant=base", "--replace-all"]);
  assert.equal(r.status, 0, r.stderr);
  assert.match(r.stdout, NOT_REPORTED);
  assert.match(r.stdout, /Reporting only \(non-interactive\)/);
  assert.ok(gsdPresent(dir), "--replace-all silently uninstalled a foreign product");
  for (const rel of GSD_REMOVED) assert.ok(existsSync(join(dir, rel)), `removed without consent: ${rel}`);
  assert.deepEqual(batches(dir), []);
  assert.equal(JSON.parse(readFileSync(join(dir, "settings.json"), "utf8")).hooks.Notification.length, 1,
    "report-only must not edit settings.json");
  rmSync(dir, { recursive: true, force: true });
});

test("the detector never fires on full, nor when gsd-core is absent", () => {
  const full = mkdtempSync(join(tmpdir(), "cc-gsd-full-"));
  plantGsdCore(full);
  const rf = run(full, ["--variant=full", "--uninstall-gsd", "--skip-all"]);
  assert.equal(rf.status, 0, rf.stderr);
  assert.doesNotMatch(rf.stdout, NOT_REPORTED);
  assert.ok(gsdPresent(full), "full profile removed gsd-core");
  assert.deepEqual(batches(full), []);
  rmSync(full, { recursive: true, force: true });

  const none = mkdtempSync(join(tmpdir(), "cc-gsd-none-"));
  const rn = run(none, ["--variant=base", "--uninstall-gsd", "--skip-all"]);
  assert.equal(rn.status, 0, rn.stderr);
  assert.doesNotMatch(rn.stdout, NOT_REPORTED);
  assert.deepEqual(batches(none), []);
  rmSync(none, { recursive: true, force: true });
});

test("the interactive prompt defaults to no; only an explicit yes removes anything", () => {
  for (const answer of ["n\n", "\n"]) {
    const dir = mkdtempSync(join(tmpdir(), "cc-gsd-no-"));
    plantGsdCore(dir);
    const r = runTty(dir, ["--variant=base", "--skip-all"], answer);
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /Move all of it to the cleanup trash\? \(y\/N\)/);
    assert.ok(gsdPresent(dir), `answer ${JSON.stringify(answer)} removed gsd-core`);
    assert.deepEqual(batches(dir), []);
    rmSync(dir, { recursive: true, force: true });
  }
  const yes = mkdtempSync(join(tmpdir(), "cc-gsd-yes-"));
  plantGsdCore(yes);
  const r = runTty(yes, ["--variant=base", "--skip-all"], "y\n");
  assert.equal(r.status, 0, r.stderr);
  assert.ok(!gsdPresent(yes), "an explicit yes did not remove gsd-core");
  assert.equal(batches(yes).length, 1);
  rmSync(yes, { recursive: true, force: true });
});

test("phase3 design-stack files ship in every profile; test files excluded", () => {
  const wanted = [
    "bin/install-design-stack.mjs",
    "bin/lib/design-stack.mjs",
    "hooks/lib/impeccable-promax-graft.mjs",
  ];
  for (const variant of ["full", "base", "lite"]) {
    const v = resolveVariant({ repoRoot: ROOT, variant });
    for (const f of wanted) assert.ok(v.rels.includes(f), `${f} must ship in ${variant}`);
    assert.ok(!v.rels.some((r) => r.endsWith(".test.mjs")), `no test files in ${variant}`);
  }
});
