import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, readFileSync, mkdirSync, rmSync, readdirSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { resolveVariant } from "./variants.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const run = (dir, args) => spawnSync(process.execPath, [join(ROOT, "setup.mjs"), ...args],
  { encoding: "utf8", env: { ...process.env, CLAUDE_CONFIG_DIR: dir, CLAUDE_SETUP_SKIP_PLUGINS: "1" }, timeout: 120000 });

function walk(dir, rel = "") {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const r = rel ? `${rel}/${e.name}` : e.name;
    if (e.isDirectory()) out.push(...walk(join(dir, e.name), r));
    else out.push(r);
  }
  return out;
}
const FOREIGN = ["settings.local.json", "projects/p/notes.md", "memory/MEMORY.md", "skills/graphify/SKILL.md"];
function plantForeign(dir) {
  for (const f of FOREIGN) { mkdirSync(join(dir, dirname(f)), { recursive: true }); writeFileSync(join(dir, f), `foreign:${f}`); }
}
function assertForeignIntact(dir) {
  for (const f of FOREIGN) assert.equal(readFileSync(join(dir, f), "utf8"), `foreign:${f}`, `foreign file clobbered: ${f}`);
}
function readManifest(dir) {
  return JSON.parse(readFileSync(join(dir, "state/bundle-manifest.json"), "utf8"));
}
// Every rel in `rels` must exist on disk, and every installed file NOT accounted for by the
// installer's own generated-outside-V.rels paths (state/, settings.json, CLAUDE.md) or a planted
// FOREIGN fixture must be IN `rels` - i.e. no surplus. Mirrors the "lite install" test's inline
// checks above, factored out so base (and future profiles) can reuse it.
function assertTreeEquals(dir, rels) {
  const installed = new Set(walk(dir));
  for (const rel of rels) assert.ok(installed.has(rel), `missing: ${rel}`);
  for (const rel of installed)
    if (!rel.startsWith("state/") && rel !== "settings.json" && rel !== "CLAUDE.md" && !FOREIGN.includes(rel))
      assert.ok(rels.includes(rel), `unexpected: ${rel}`);
}

test("no *.test.mjs leaks into any resolved profile (alwaysExclude)", () => {
  for (const variant of ["full", "base", "lite"]) {
    const v = resolveVariant({ repoRoot: ROOT, variant });
    const leaked = v.rels.filter((r) => r.endsWith(".test.mjs"));
    assert.deepEqual(leaked, [], `test files leaked into ${variant}: ${leaked.join(", ")}`);
  }
});

test("lite install: exact tree, 7 hooks, no statusLine, manifest.variant", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-lite-"));
  plantForeign(dir);
  const r = run(dir, ["--variant=lite", "--replace-all"]);
  assert.equal(r.status, 0, r.stderr);
  const v = resolveVariant({ repoRoot: ROOT, variant: "lite" });
  const installed = new Set(walk(dir));
  for (const rel of v.rels) assert.ok(installed.has(rel), `missing: ${rel}`);
  // CLAUDE.md is ASSEMBLED (not a payload rel - payload/claude-md/** is a build input, see
  // assemble-claude-md.mjs) so it's whitelisted here the same way settings.json/state/ are:
  // generated by setup.mjs itself, not mirrored 1:1 from V.rels.
  for (const rel of installed)
    if (!rel.startsWith("state/") && rel !== "settings.json" && rel !== "CLAUDE.md" && !FOREIGN.includes(rel))
      assert.ok(v.rels.includes(rel), `unexpected: ${rel}`);
  const settings = JSON.parse(readFileSync(join(dir, "settings.json"), "utf8"));
  const scripts = new Set();
  for (const entries of Object.values(settings.hooks || {}))
    for (const e of entries) for (const h of (e.hooks || []))
      for (const a of (h.args || [])) scripts.add(String(a).split(/[\\/]/).pop());
  assert.equal(scripts.size, 7);
  assert.ok(!("statusLine" in settings));
  assert.equal(JSON.parse(readFileSync(join(dir, "state/bundle-manifest.json"), "utf8")).variant, "lite");
  // lite CLAUDE.md is the overlay version
  assert.match(readFileSync(join(dir, "CLAUDE.md"), "utf8"), /lite variant/);
  for (const f of FOREIGN) assert.equal(readFileSync(join(dir, f), "utf8"), `foreign:${f}`);
  rmSync(dir, { recursive: true, force: true });
});

test("switch full->lite prunes surplus; lite->full restores; foreign untouched", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-sw-"));
  plantForeign(dir);
  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")));
  assert.equal(run(dir, ["--variant=lite", "--replace-all"]).status, 0);
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook not pruned");
  assert.ok(!existsSync(join(dir, "hooks/lib/context-mode-gsd-agents.mjs")), "gsd lib not pruned (name-gate bypass broken?)");
  assert.ok(!existsSync(join(dir, "gsd-defaults.partial.json")), "gsd-defaults mirror not pruned");
  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "full files not restored");
  assert.equal(JSON.parse(readFileSync(join(dir, "state/bundle-manifest.json"), "utf8")).variant, "full");
  for (const f of FOREIGN) assert.equal(readFileSync(join(dir, f), "utf8"), `foreign:${f}`);
  rmSync(dir, { recursive: true, force: true });
});

test("manifest without variant field = full (no surplus prune on full reinstall)", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-legacy-"));
  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  const mPath = join(dir, "state/bundle-manifest.json");
  const m = JSON.parse(readFileSync(mPath, "utf8"));
  delete m.variant;                      // simulate pre-variant bundle
  writeFileSync(mPath, JSON.stringify(m, null, 2));
  const r = run(dir, ["--replace-all"]); // no flag, non-TTY -> detected = full
  assert.equal(r.status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")));
  rmSync(dir, { recursive: true, force: true });
});

test("manifest profile round-trips and falls back to variant", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-fallback-"));
  assert.equal(run(dir, ["--variant=base", "--replace-all"]).status, 0);
  assert.equal(readManifest(dir).profile, "base");
  assert.equal(readManifest(dir).variant, "base");

  // profile present, variant absent -> profile wins (the current dual-write's primary key).
  const mPath = join(dir, "state/bundle-manifest.json");
  let m = readManifest(dir);
  delete m.variant;
  writeFileSync(mPath, JSON.stringify(m, null, 2));
  assert.equal(run(dir, ["--replace-all"]).status, 0); // no --variant flag: detected from manifest
  assert.equal(readManifest(dir).profile, "base");
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "should stay on base, not fall back to full");

  // NEITHER key present -> true legacy fallback path ("full" default), the case the old
  // "manifest without variant field" test claimed to cover but didn't (it left .profile behind).
  m = readManifest(dir);
  delete m.profile;
  delete m.variant;
  writeFileSync(mPath, JSON.stringify(m, null, 2));
  assert.equal(run(dir, ["--replace-all"]).status, 0);
  assert.equal(readManifest(dir).profile, "full");
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "neither key present -> falls back to full");
  rmSync(dir, { recursive: true, force: true });
});

test("base install: exact tree, base keep-set present, gsd absent, manifest.profile", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-base-"));
  plantForeign(dir);
  const r = run(dir, ["--variant=base", "--skip-all"]);
  assert.equal(r.status, 0, r.stderr);
  const v = resolveVariant({ repoRoot: ROOT, variant: "base" });
  assertTreeEquals(dir, v.rels);
  assert.ok(existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")), "base universal infra hook missing");
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook should be absent on base");
  assert.equal(readManifest(dir).profile, "base");
  assertForeignIntact(dir);
  rmSync(dir, { recursive: true, force: true });
});

test("full->base->lite prunes GSD then universal infra; foreign untouched", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-transitions-"));
  plantForeign(dir);

  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")));
  assert.ok(existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")));
  assertForeignIntact(dir);

  // full -> base: GSD-everything pruned, universal infra (base's own keep-set) stays.
  assert.equal(run(dir, ["--variant=base", "--replace-all"]).status, 0);
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook not pruned on full->base");
  assert.ok(!existsSync(join(dir, "hooks/lib/context-mode-gsd-agents.mjs")), "gsd lib not pruned on full->base");
  assert.ok(!existsSync(join(dir, "gsd-defaults.partial.json")), "gsd-defaults mirror not pruned on full->base");
  assert.ok(existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")), "universal infra wrongly pruned on full->base");
  assert.equal(readManifest(dir).profile, "base");
  assertForeignIntact(dir);

  // base -> lite: the universal infra base kept now gets pruned too.
  assert.equal(run(dir, ["--variant=lite", "--replace-all"]).status, 0);
  assert.ok(!existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")), "universal infra not pruned on base->lite");
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook still absent on lite");
  assert.equal(readManifest(dir).profile, "lite");
  assertForeignIntact(dir);

  rmSync(dir, { recursive: true, force: true });
});

test("augment toggle: base + --configure-neo4j=on adds files; =off prunes them, no manual chain", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-augment-"));
  const neo4jFile = join(dir, "bin/lib/neo4j-config.mjs");

  assert.equal(run(dir, ["--variant=base", "--skip-all"]).status, 0);
  assert.ok(!existsSync(neo4jFile), "neo4j should be off by default on base");
  assert.deepEqual(readManifest(dir).activeOptional, []);

  assert.equal(run(dir, ["--variant=base", "--configure-neo4j=on", "--skip-all"]).status, 0);
  assert.ok(existsSync(neo4jFile), "--configure-neo4j=on should add the file in-process");
  assert.deepEqual(readManifest(dir).activeOptional, ["neo4j"]);

  assert.equal(run(dir, ["--variant=base", "--configure-neo4j=off", "--skip-all"]).status, 0);
  assert.ok(!existsSync(neo4jFile), "--configure-neo4j=off should prune the file in-process");
  assert.deepEqual(readManifest(dir).activeOptional, []);

  rmSync(dir, { recursive: true, force: true });
});

test("lite build ships the AI-dev-mode (A) files", () => {
  const v = resolveVariant({ repoRoot: ROOT, variant: "lite" });
  for (const p of [
    "hooks/inject-axes.mjs",
    "hooks/lib/inject-axes.mjs",
    "hooks/lib/verbosity-rules.mjs",
    "hooks/lib/verbosity-lite-rule.md",
    "commands/aidev.md",
  ]) {
    assert.ok(v.rels.includes(p), `${p} must be in lite`);
  }
});

test("--dry-run writes nothing for both variants", () => {
  for (const variant of ["lite", "full"]) {
    const dir = mkdtempSync(join(tmpdir(), "cc-dry-"));
    const r = run(dir, [`--variant=${variant}`, "--dry-run", "--skip-all"]);
    assert.equal(r.status, 0, r.stderr);
    assert.deepEqual(walk(dir), [], `dry-run wrote files (${variant})`);
    rmSync(dir, { recursive: true, force: true });
  }
});
