import { test, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, readFileSync, mkdirSync, rmSync, readdirSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { spawnSync, spawn } from "node:child_process";
import { resolveVariant } from "./variants.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const run = (dir, args) => spawnSync(process.execPath, [join(ROOT, "setup.mjs"), ...args],
  { encoding: "utf8", env: { ...process.env, CLAUDE_CONFIG_DIR: dir, CLAUDE_SETUP_SKIP_PLUGINS: "1" }, timeout: 120000 });

function walk(dir, rel = "") {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const r = rel ? `${rel}/${e.name}` : e.name;
    if (e.isDirectory()) out.push(...walk(join(dir, e.name), r));
    else out.push(r);
  }
  return out;
}
const FOREIGN = ["settings.local.json", "projects/p/notes.md", "memory/MEMORY.md", "skills/graphify/SKILL.md"];
function plantForeign(dir) {
  for (const f of FOREIGN) { mkdirSync(join(dir, dirname(f)), { recursive: true }); writeFileSync(join(dir, f), `foreign:${f}`); }
}
function assertForeignIntact(dir) {
  for (const f of FOREIGN) assert.equal(readFileSync(join(dir, f), "utf8"), `foreign:${f}`, `foreign file clobbered: ${f}`);
}
function readManifest(dir) {
  return JSON.parse(readFileSync(join(dir, "state/bundle-manifest.json"), "utf8"));
}
// Every rel in `rels` must exist on disk, and every installed file NOT accounted for by the
// installer's own generated-outside-V.rels paths (state/, settings.json, CLAUDE.md) or a planted
// FOREIGN fixture must be IN `rels` - i.e. no surplus. Mirrors the "lite install" test's inline
// checks above, factored out so base (and future profiles) can reuse it.
function assertTreeEquals(dir, rels) {
  const installed = new Set(walk(dir));
  for (const rel of rels) assert.ok(installed.has(rel), `missing: ${rel}`);
  for (const rel of installed)
    if (!rel.startsWith("state/") && rel !== "settings.json" && rel !== "CLAUDE.md" && !FOREIGN.includes(rel))
      assert.ok(rels.includes(rel), `unexpected: ${rel}`);
}

test("no *.test.mjs leaks into any resolved profile (alwaysExclude)", () => {
  for (const variant of ["full", "base", "lite"]) {
    const v = resolveVariant({ repoRoot: ROOT, variant });
    const leaked = v.rels.filter((r) => r.endsWith(".test.mjs"));
    assert.deepEqual(leaked, [], `test files leaked into ${variant}: ${leaked.join(", ")}`);
  }
});

test("lite install: exact tree, 7 hooks, no statusLine, manifest.variant", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-lite-"));
  plantForeign(dir);
  const r = run(dir, ["--variant=lite", "--replace-all"]);
  assert.equal(r.status, 0, r.stderr);
  const v = resolveVariant({ repoRoot: ROOT, variant: "lite" });
  const installed = new Set(walk(dir));
  for (const rel of v.rels) assert.ok(installed.has(rel), `missing: ${rel}`);
  // CLAUDE.md is ASSEMBLED (not a payload rel - payload/claude-md/** is a build input, see
  // assemble-claude-md.mjs) so it's whitelisted here the same way settings.json/state/ are:
  // generated by setup.mjs itself, not mirrored 1:1 from V.rels.
  for (const rel of installed)
    if (!rel.startsWith("state/") && rel !== "settings.json" && rel !== "CLAUDE.md" && !FOREIGN.includes(rel))
      assert.ok(v.rels.includes(rel), `unexpected: ${rel}`);
  const settings = JSON.parse(readFileSync(join(dir, "settings.json"), "utf8"));
  const scripts = new Set();
  for (const entries of Object.values(settings.hooks || {}))
    for (const e of entries) for (const h of (e.hooks || []))
      for (const a of (h.args || [])) scripts.add(String(a).split(/[\\/]/).pop());
  assert.equal(scripts.size, 7);
  assert.ok(!("statusLine" in settings));
  assert.equal(JSON.parse(readFileSync(join(dir, "state/bundle-manifest.json"), "utf8")).variant, "lite");
  // lite CLAUDE.md is the overlay version
  assert.match(readFileSync(join(dir, "CLAUDE.md"), "utf8"), /lite variant/);
  for (const f of FOREIGN) assert.equal(readFileSync(join(dir, f), "utf8"), `foreign:${f}`);
  rmSync(dir, { recursive: true, force: true });
});

test("switch full->lite prunes surplus; lite->full restores; foreign untouched", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-sw-"));
  plantForeign(dir);
  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")));
  assert.equal(run(dir, ["--variant=lite", "--replace-all"]).status, 0);
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook not pruned");
  assert.ok(!existsSync(join(dir, "hooks/lib/context-mode-gsd-agents.mjs")), "gsd lib not pruned (name-gate bypass broken?)");
  assert.ok(!existsSync(join(dir, "gsd-defaults.partial.json")), "gsd-defaults mirror not pruned");
  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "full files not restored");
  assert.equal(JSON.parse(readFileSync(join(dir, "state/bundle-manifest.json"), "utf8")).variant, "full");
  for (const f of FOREIGN) assert.equal(readFileSync(join(dir, f), "utf8"), `foreign:${f}`);
  rmSync(dir, { recursive: true, force: true });
});

test("manifest without variant field = full (no surplus prune on full reinstall)", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-legacy-"));
  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  const mPath = join(dir, "state/bundle-manifest.json");
  const m = JSON.parse(readFileSync(mPath, "utf8"));
  delete m.variant;                      // simulate pre-variant bundle
  writeFileSync(mPath, JSON.stringify(m, null, 2));
  const r = run(dir, ["--replace-all"]); // no flag, non-TTY -> detected = full
  assert.equal(r.status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")));
  rmSync(dir, { recursive: true, force: true });
});

test("manifest profile round-trips and falls back to variant", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-fallback-"));
  assert.equal(run(dir, ["--variant=base", "--replace-all"]).status, 0);
  assert.equal(readManifest(dir).profile, "base");
  assert.equal(readManifest(dir).variant, "base");

  // profile present, variant absent -> profile wins (the current dual-write's primary key).
  const mPath = join(dir, "state/bundle-manifest.json");
  let m = readManifest(dir);
  delete m.variant;
  writeFileSync(mPath, JSON.stringify(m, null, 2));
  assert.equal(run(dir, ["--replace-all"]).status, 0); // no --variant flag: detected from manifest
  assert.equal(readManifest(dir).profile, "base");
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "should stay on base, not fall back to full");

  // NEITHER key present -> true legacy fallback path ("full" default), the case the old
  // "manifest without variant field" test claimed to cover but didn't (it left .profile behind).
  m = readManifest(dir);
  delete m.profile;
  delete m.variant;
  writeFileSync(mPath, JSON.stringify(m, null, 2));
  assert.equal(run(dir, ["--replace-all"]).status, 0);
  assert.equal(readManifest(dir).profile, "full");
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "neither key present -> falls back to full");
  rmSync(dir, { recursive: true, force: true });
});

test("base install: exact tree, base keep-set present, gsd absent, manifest.profile", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-base-"));
  plantForeign(dir);
  const r = run(dir, ["--variant=base", "--skip-all"]);
  assert.equal(r.status, 0, r.stderr);
  const v = resolveVariant({ repoRoot: ROOT, variant: "base" });
  assertTreeEquals(dir, v.rels);
  assert.ok(existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")), "base universal infra hook missing");
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook should be absent on base");
  assert.equal(readManifest(dir).profile, "base");
  assertForeignIntact(dir);
  rmSync(dir, { recursive: true, force: true });
});

test("full->base->lite prunes GSD then universal infra; foreign untouched", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-transitions-"));
  plantForeign(dir);

  assert.equal(run(dir, ["--variant=full", "--replace-all"]).status, 0);
  assert.ok(existsSync(join(dir, "hooks/gsd-context-meter.mjs")));
  assert.ok(existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")));
  assertForeignIntact(dir);

  // full -> base: GSD-everything pruned, universal infra (base's own keep-set) stays.
  assert.equal(run(dir, ["--variant=base", "--replace-all"]).status, 0);
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook not pruned on full->base");
  assert.ok(!existsSync(join(dir, "hooks/lib/context-mode-gsd-agents.mjs")), "gsd lib not pruned on full->base");
  assert.ok(!existsSync(join(dir, "gsd-defaults.partial.json")), "gsd-defaults mirror not pruned on full->base");
  assert.ok(existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")), "universal infra wrongly pruned on full->base");
  assert.equal(readManifest(dir).profile, "base");
  assertForeignIntact(dir);

  // base -> lite: the universal infra base kept now gets pruned too.
  assert.equal(run(dir, ["--variant=lite", "--replace-all"]).status, 0);
  assert.ok(!existsSync(join(dir, "hooks/bg-supervision-nudge.mjs")), "universal infra not pruned on base->lite");
  assert.ok(!existsSync(join(dir, "hooks/gsd-context-meter.mjs")), "gsd hook still absent on lite");
  assert.equal(readManifest(dir).profile, "lite");
  assertForeignIntact(dir);

  rmSync(dir, { recursive: true, force: true });
});

test("augment toggle: base + --configure-neo4j=on adds files; =off prunes them, no manual chain", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-augment-"));
  const neo4jFile = join(dir, "bin/lib/neo4j-config.mjs");

  assert.equal(run(dir, ["--variant=base", "--skip-all"]).status, 0);
  assert.ok(!existsSync(neo4jFile), "neo4j should be off by default on base");
  assert.deepEqual(readManifest(dir).activeOptional, []);

  assert.equal(run(dir, ["--variant=base", "--configure-neo4j=on", "--skip-all"]).status, 0);
  assert.ok(existsSync(neo4jFile), "--configure-neo4j=on should add the file in-process");
  assert.deepEqual(readManifest(dir).activeOptional, ["neo4j"]);

  assert.equal(run(dir, ["--variant=base", "--configure-neo4j=off", "--skip-all"]).status, 0);
  assert.ok(!existsSync(neo4jFile), "--configure-neo4j=off should prune the file in-process");
  assert.deepEqual(readManifest(dir).activeOptional, []);

  rmSync(dir, { recursive: true, force: true });
});

test("lite build ships the AI-dev-mode (A) files", () => {
  const v = resolveVariant({ repoRoot: ROOT, variant: "lite" });
  for (const p of [
    "hooks/inject-axes.mjs",
    "hooks/lib/inject-axes.mjs",
    "hooks/lib/verbosity-rules.mjs",
    "hooks/lib/verbosity-lite-rule.md",
    "commands/aidev.md",
  ]) {
    assert.ok(v.rels.includes(p), `${p} must be in lite`);
  }
});

test("--dry-run writes nothing for both variants", () => {
  for (const variant of ["lite", "full"]) {
    const dir = mkdtempSync(join(tmpdir(), "cc-dry-"));
    const r = run(dir, [`--variant=${variant}`, "--dry-run", "--skip-all"]);
    assert.equal(r.status, 0, r.stderr);
    assert.deepEqual(walk(dir), [], `dry-run wrote files (${variant})`);
    rmSync(dir, { recursive: true, force: true });
  }
});

/* ---------- foreign gsd-core detector (base/lite only) ----------
 * `run()` above is always non-TTY (spawnSync pipes stdin) and so can never reach an interactive
 * branch. runTty() launches setup.mjs through a driver that forces process.stdin.isTTY first, and
 * answers arrive on stdin. GRAPHIFY_PYTHON points at a file that exists so findGraphifyPython()
 * succeeds and its install prompt - the one prompt whose presence would otherwise depend on the
 * machine - never fires.
 * Answers are keyed by prompt text and written one at a time, only once the prompt has actually
 * been printed. Preloading them all on stdin does not work: the first readline buffers whatever is
 * available and discards the remainder on close(), so answer two would silently never arrive and
 * every later question would read EOF. Keying also means a prompt added to setup.mjs later gets a
 * bare Enter instead of eating the answer meant for the question under test. */
const TTY_DIR = mkdtempSync(join(tmpdir(), "cc-tty-"));
const TTY_DRIVER = join(TTY_DIR, "force-tty.mjs");
writeFileSync(TTY_DRIVER, "process.stdin.isTTY = true;\nawait import(process.env.SETUP_URL);\n");
after(() => rmSync(TTY_DIR, { recursive: true, force: true }));
function runTty(dir, args, answers = []) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [TTY_DRIVER, ...args], {
      env: { ...process.env, CLAUDE_CONFIG_DIR: dir, CLAUDE_SETUP_SKIP_PLUGINS: "1",
        GRAPHIFY_PYTHON: process.execPath, SETUP_URL: pathToFileURL(join(ROOT, "setup.mjs")).href },
    });
    const pending = answers.map((a) => [...a]);
    let stdout = "", stderr = "", lastAnswered = null;
    const killer = setTimeout(() => child.kill(), 120000);
    child.stdout.on("data", (d) => {
      stdout += String(d);
      if (!/> $/.test(stdout)) return;
      const prompt = stdout.slice(stdout.lastIndexOf("\n") + 1);
      if (prompt === lastAnswered) return;              // terminal-mode readline can re-render one prompt
      lastAnswered = prompt;
      const i = pending.findIndex(([m]) => prompt.includes(m));
      child.stdin.write((i === -1 ? "" : pending.splice(i, 1)[0][1]) + "\n");
      // readline in terminal mode leaves stdin resumed after close(), so the child outlives its own
      // work unless the pipe is shut. Safe once the keyed answer is spent: it is the last question
      // the run asks, and if that ever stops being true the run hangs and the test says so.
      if (answers.length && !pending.length) child.stdin.end();
    });
    child.stderr.on("data", (d) => { stderr += String(d); });
    child.on("close", (status) => { clearTimeout(killer); resolve({ status, stdout, stderr }); });
  });
}
const GSD_FIXTURE = {
  "gsd-core/VERSION": "0.0.0-test\n",
  "gsd-core/lib/orchestrate.mjs": "x".repeat(3000),
  "skills/gsd-probe/SKILL.md": "x",
  "agents/gsd-planner.md": "x",
  "hooks/gsd-probe.mjs": "x",
  "hooks/gsd-legacy.js": "x",
  "hooks/lib/gsd-probe-lib.mjs": "x",
};
const GSD_REMOVED = ["gsd-core", "skills/gsd-probe", "agents/gsd-planner.md", "hooks/gsd-probe.mjs",
  "hooks/gsd-legacy.js", "hooks/lib/gsd-probe-lib.mjs"];
// Both registration shapes on purpose. The args form is this bundle's; the bare quoted command
// line with no args at all is what every hook of a real gsd-core install actually looks like, and
// a matcher that only reads `args` leaves it registered after the file underneath it has moved.
const cmdHook = (command) => ({ matcher: "", hooks: [{ type: "command", command }] });
function plantGsdCore(dir, { settings = true } = {}) {
  for (const [rel, body] of Object.entries(GSD_FIXTURE)) {
    mkdirSync(join(dir, dirname(rel)), { recursive: true });
    writeFileSync(join(dir, rel), body);
  }
  if (!settings) return;
  const fwd = (rel) => join(dir, rel).replace(/\\/g, "/");
  // Registered under an event settings.partial.json never declares, so the assertions below see the
  // detector's own filter and not the settings merge's claim-our-slots pass.
  writeFileSync(join(dir, "settings.json"), JSON.stringify({
    hooks: {
      Notification: [
        { matcher: "", hooks: [{ type: "command", command: "node", args: [join(dir, "hooks", "gsd-probe.mjs")] }] },
        cmdHook(`"C:/Program Files/nodejs/node.exe" "${fwd("hooks/gsd-legacy.js")}"`),
        cmdHook(`"${fwd("hooks/gsd-legacy.js")}" --quiet`),
        cmdHook(`node "${fwd("hooks/lib/gsd-probe-lib.mjs")}"`),
        cmdHook(`node "${fwd("hooks/session-init.mjs")}"`),
      ],
    },
  }, null, 2) + "\n");
}
const gsdPresent = (dir) => existsSync(join(dir, "gsd-core/VERSION"));
const batches = (dir) => (existsSync(join(dir, ".cleanup-trash")) ? readdirSync(join(dir, ".cleanup-trash")) : []);
const NOT_REPORTED = /is installed here and is not part of this bundle/;

test("--uninstall-gsd moves gsd-core to a trash batch, backs settings up first, drops only gsd hooks", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-gsd-"));
  plantGsdCore(dir);

  const dry = run(dir, ["--variant=base", "--uninstall-gsd", "--dry-run", "--skip-all"]);
  assert.equal(dry.status, 0, dry.stderr);
  assert.match(dry.stdout, /\[dry-run\] would move \d+ path\(s\)/);
  assert.ok(gsdPresent(dir), "dry-run removed something");
  assert.deepEqual(batches(dir), []);

  const r = run(dir, ["--variant=base", "--uninstall-gsd", "--skip-all"]);
  assert.equal(r.status, 0, r.stderr);
  assert.match(r.stdout, /gsd-core 0\.0\.0-test is installed here and is not part of this bundle/);
  for (const rel of GSD_REMOVED) assert.ok(!existsSync(join(dir, rel)), `not removed: ${rel}`);

  const ts = batches(dir);
  assert.equal(ts.length, 1, `expected exactly one trash batch, got ${ts.join(", ")}`);
  const batch = join(dir, ".cleanup-trash", ts[0]);
  assert.ok(existsSync(join(batch, "manifest.json")), "batch manifest missing");
  assert.ok(r.stdout.includes(`trash batch: ${batch.replace(/\\/g, "/")}`), "batch path not printed before the moves");
  const backup = join(batch, "settings.json.pre-gsd-uninstall");
  assert.ok(existsSync(backup), "pre-edit settings copy missing from the batch");
  assert.equal(JSON.parse(readFileSync(backup, "utf8")).hooks.Notification.length, 5, "backup is not the PRE-edit copy");

  // Three gsd hook registrations go (args form, interpreter+quoted path, quoted path + trailing
  // arg); the hooks/lib entry and the unrelated hook stay.
  const settings = JSON.parse(readFileSync(join(dir, "settings.json"), "utf8"));
  assert.equal(settings.hooks.Notification.length, 2, "wrong set of gsd hook registrations removed");
  const left = JSON.stringify(settings.hooks.Notification);
  assert.ok(!/hooks\/gsd-probe\.mjs|hooks\/gsd-legacy\.js/.test(left), "a gsd hook registration survived");
  assert.ok(left.includes("gsd-probe-lib.mjs") && left.includes("session-init.mjs"), "a non-gsd-hook entry was dropped");
  assert.match(r.stdout, /removed 3 gsd-\* hook registration\(s\)/);

  // restoreBatch deletes the whole batch (backup included), so the cp must be printed FIRST; and
  // claude-cleanup.mjs reads CLAUDE_CONFIG_DIR, not its own location, so a relocated dir must
  // travel with the command or the restore silently targets ~/.claude.
  const cpAt = r.stdout.indexOf(`cp "`);
  const restoreAt = r.stdout.indexOf(`restore --ts ${ts[0]}`);
  assert.ok(cpAt !== -1, "rollback did not print a cp for settings.json");
  assert.ok(restoreAt !== -1, "rollback did not print the batch restore command with this run's ts");
  assert.ok(cpAt < restoreAt, "rollback prints restore before cp - restoring first destroys the backup");
  assert.ok(r.stdout.includes(`CLAUDE_CONFIG_DIR="${dir.replace(/\\/g, "/")}" node "`),
    "relocated config dir not carried into the printed restore command");
  rmSync(dir, { recursive: true, force: true });
});

test("a bulk flag is never consent, and never a prompt either", async () => {
  for (const bulk of ["--replace-all", "--merge-all"]) {
    const dir = mkdtempSync(join(tmpdir(), "cc-gsd-bulk-"));
    plantGsdCore(dir);
    // Non-TTY and forced-TTY both: a bulk flag means "never ask", so the PTY case must not block.
    for (const launch of [async (d, a) => run(d, a), runTty]) {
      const r = await launch(dir, ["--variant=base", bulk]);
      assert.equal(r.status, 0, r.stderr);
      assert.match(r.stdout, NOT_REPORTED);
      assert.match(r.stdout, /Reporting only \(non-interactive\)/);
      assert.doesNotMatch(r.stdout, /Move all of it to the cleanup trash/, `${bulk} prompted instead of reporting`);
      assert.ok(gsdPresent(dir), `${bulk} silently uninstalled a foreign product`);
      for (const rel of GSD_REMOVED) assert.ok(existsSync(join(dir, rel)), `removed without consent: ${rel}`);
      assert.deepEqual(batches(dir), []);
      assert.equal(JSON.parse(readFileSync(join(dir, "settings.json"), "utf8")).hooks.Notification.length, 5,
        "report-only must not edit settings.json");
    }
    rmSync(dir, { recursive: true, force: true });
  }
});

test("a file this bundle owns is never claimed as foreign, even when the stale prune declined it", () => {
  const dir = mkdtempSync(join(tmpdir(), "cc-gsd-downgrade-"));
  assert.equal(run(dir, ["--variant=full", "--skip-all"]).status, 0);
  const ours = ["hooks/gsd-context-meter.mjs", "hooks/gsd-config-patch.mjs",
    "hooks/lib/gsd-agent-patches.mjs", "hooks/lib/gsd-skill-patches.mjs", "agents/gsd-task-verifier.md"];
  for (const rel of ours) assert.ok(existsSync(join(dir, rel)), `full install is missing ${rel}`);
  plantGsdCore(dir, { settings: false });

  // Non-TTY without a bulk flag: pruneStale reports and removes nothing, so every one of `ours` is
  // still on disk and absent from THIS run's manifest - the exact shape that used to be swept up.
  const r = run(dir, ["--variant=base", "--uninstall-gsd"]);
  assert.equal(r.status, 0, r.stderr);
  assert.match(r.stdout, /non-interactive: not removed/, "pruneStale unexpectedly pruned - test no longer covers its case");
  assert.ok(!gsdPresent(dir), "the foreign gsd-core was not removed");
  for (const rel of ours) assert.ok(existsSync(join(dir, rel)), `bundle-owned file claimed as foreign: ${rel}`);
  rmSync(dir, { recursive: true, force: true });
});

test("the detector never fires on full, nor when gsd-core is absent", () => {
  const full = mkdtempSync(join(tmpdir(), "cc-gsd-full-"));
  plantGsdCore(full);
  const rf = run(full, ["--variant=full", "--uninstall-gsd", "--skip-all"]);
  assert.equal(rf.status, 0, rf.stderr);
  assert.doesNotMatch(rf.stdout, NOT_REPORTED);
  assert.ok(gsdPresent(full), "full profile removed gsd-core");
  assert.deepEqual(batches(full), []);
  rmSync(full, { recursive: true, force: true });

  const none = mkdtempSync(join(tmpdir(), "cc-gsd-none-"));
  const rn = run(none, ["--variant=base", "--uninstall-gsd", "--skip-all"]);
  assert.equal(rn.status, 0, rn.stderr);
  assert.doesNotMatch(rn.stdout, NOT_REPORTED);
  assert.deepEqual(batches(none), []);
  rmSync(none, { recursive: true, force: true });
});

test("the interactive prompt defaults to no; only an explicit yes removes anything", async () => {
  const TTY_ARGS = ["--variant=base", "--configure-neo4j=off", "--enable-update-check"];
  const PROMPT = "Move all of it to the cleanup trash?";
  const asked = (r) => {
    assert.match(r.stdout, /left unchanged \(CLAUDE_CONFIG_DIR not set\)/, "an earlier prompt was not answered");
    assert.ok(r.stdout.includes(PROMPT), "the detector never asked");
  };
  for (const answer of ["n", ""]) {
    const dir = mkdtempSync(join(tmpdir(), "cc-gsd-no-"));
    plantGsdCore(dir, { settings: false });
    const r = await runTty(dir, TTY_ARGS, [[PROMPT, answer]]);
    assert.equal(r.status, 0, r.stderr);
    asked(r);
    assert.ok(gsdPresent(dir), `answer ${JSON.stringify(answer)} removed gsd-core`);
    assert.deepEqual(batches(dir), []);
    rmSync(dir, { recursive: true, force: true });
  }
  const yes = mkdtempSync(join(tmpdir(), "cc-gsd-yes-"));
  plantGsdCore(yes, { settings: false });
  const r = await runTty(yes, TTY_ARGS, [[PROMPT, "y"]]);
  assert.equal(r.status, 0, r.stderr);
  asked(r);
  assert.ok(!gsdPresent(yes), "an explicit yes did not remove gsd-core");
  assert.equal(batches(yes).length, 1);
  rmSync(yes, { recursive: true, force: true });
});

test("phase3 design-stack files ship in every profile; test files excluded", () => {
  const wanted = [
    "bin/install-design-stack.mjs",
    "bin/lib/design-stack.mjs",
    "hooks/lib/impeccable-promax-graft.mjs",
  ];
  for (const variant of ["full", "base", "lite"]) {
    const v = resolveVariant({ repoRoot: ROOT, variant });
    for (const f of wanted) assert.ok(v.rels.includes(f), `${f} must ship in ${variant}`);
    assert.ok(!v.rels.some((r) => r.endsWith(".test.mjs")), `no test files in ${variant}`);
  }
});
